name: manual approval
on: push
jobs:
  Development:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: running on Development env
        run: echo "Dev Done"
  Production:
    runs-on: ubuntu-latest
    environment: Pro
    needs: Development
    steps:
      - name: runnin on Productions
        run: echo "Production done"  
